@extends('website.layouts.app')
@section('title','Carrito | Fitness Club Tunja')
@section('seo_robots','noindex,follow')
@push('page_styles')
<style>
.cart-alert{margin:0 auto 24px;max-width:760px;padding:16px 20px;border:1px solid #ff5577;border-radius:12px;background:rgba(150,20,55,.18);color:#ffdce4}.cart-alert strong{display:block;margin-bottom:6px;color:#ff8ca5}.cart-alert ul{margin:0;padding-left:20px}.pay-button:disabled{opacity:.65;cursor:wait}
body{background:radial-gradient(circle at top,#101026,#050509)!important;color:#fff}.shop-cart-page{padding:72px 0 110px;min-height:72vh}.cart-header{text-align:center;margin-bottom:38px}.cart-header h1{font-size:clamp(2rem,5vw,3rem);font-weight:900;text-transform:uppercase;background:linear-gradient(90deg,#8a2be2,#00f0ff);-webkit-background-clip:text;-webkit-text-fill-color:transparent}.cart-header p{color:#aaa}.cart-layout{display:grid;grid-template-columns:minmax(0,1fr) 360px;gap:24px;align-items:start}.cart-panel{background:#151527;border:1px solid rgba(255,255,255,.1);border-radius:18px;padding:26px;box-shadow:0 15px 35px rgba(0,0,0,.28)}.cart-panel h2{font-size:1.15rem;text-transform:uppercase;margin:0 0 20px}.cart-table-wrap{overflow-x:auto}.cart-table{width:100%;border-collapse:collapse}.cart-table th{color:#00e5ff;font-size:.76rem;text-transform:uppercase;text-align:left;padding:12px;border-bottom:1px solid rgba(255,255,255,.12)}.cart-table td{padding:16px 12px;color:#ddd;border-bottom:1px solid rgba(255,255,255,.08)}.cart-table input{width:65px;padding:8px;background:#0b0b16;color:#fff;border:1px solid #444;border-radius:6px;text-align:center}.cart-remove{border:0;background:none;color:#ff718b;cursor:pointer}.cart-empty{text-align:center;color:#999;padding:35px}.cart-empty a{display:inline-block;margin-top:18px}.cart-summary{display:flex;justify-content:space-between;margin-top:22px;font-size:1.1rem}.cart-summary strong{color:#00e5ff;font-size:1.45rem}.buyer-form{display:grid;gap:12px}.buyer-form label{color:#aaa;font-size:.85rem}.buyer-form input{display:block;width:100%;margin-top:6px;padding:12px;border-radius:8px;border:1px solid rgba(255,255,255,.15);background:#0b0b16;color:#fff}.pay-button,.continue-link{display:inline-flex;justify-content:center;align-items:center;width:100%;padding:14px;border:0;border-radius:25px;background:linear-gradient(90deg,#8a2be2,#00dff5);color:#fff!important;font-weight:800;text-transform:uppercase;text-decoration:none;cursor:pointer}.continue-link{margin-top:12px;background:transparent;border:1px solid rgba(0,229,255,.4)}@media(max-width:850px){.cart-layout{grid-template-columns:1fr}.cart-panel{padding:18px}}
</style>
@endpush
@section('content')
<main class="shop-cart-page"><div class="container">
<header class="cart-header"><h1>Tu carrito</h1><p>Revisa tus productos y completa tus datos para continuar al pago seguro.</p></header>
@if($errors->any())<div class="cart-alert" role="alert"><strong>No pudimos continuar con el pago:</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@if(session('error'))<div class="cart-alert" role="alert"><strong>No pudimos continuar con el pago:</strong><div>{{ session('error') }}</div></div>@endif
<div class="cart-layout">
<section class="cart-panel"><h2>Productos seleccionados</h2><div id="cart-empty" class="cart-empty" hidden>Tu carrito está vacío.<br><a class="continue-link" href="{{ url('tienda') }}">Ir a la tienda</a></div><div id="cart-content"><div class="cart-table-wrap"><table class="cart-table"><thead><tr><th>Producto</th><th>Precio</th><th>Cantidad</th><th>Total</th><th></th></tr></thead><tbody id="cart-items"></tbody></table></div><div class="cart-summary"><span>Total del pedido</span><strong id="total-price">$0</strong></div></div></section>
<aside class="cart-panel"><h2>Datos del comprador</h2><form id="checkout-form" class="buyer-form" method="POST" action="{{ route('website.pagos.iniciar') }}">@csrf<input type="hidden" name="tipo" value="tienda"><input type="hidden" name="items" id="checkout-items"><label>Nombre completo<input required name="nombre" value="{{ old('nombre', auth()->user()->name ?? '') }}" placeholder="Tu nombre"></label><label>Correo electrónico<input required type="email" name="email" value="{{ old('email', auth()->user()->email ?? '') }}" placeholder="correo@ejemplo.com"></label><label>Teléfono<input required name="telefono" value="{{ old('telefono', auth()->user()->celular ?? '') }}" placeholder="300 000 0000"></label>@guest<label>Contraseña<input required type="password" name="password" minlength="8" placeholder="Mínimo 8 caracteres"></label><label>Repite la contraseña<input required type="password" name="password_confirmation" minlength="8"></label>@endguest<button class="pay-button" type="submit">Continuar a Wompi</button><a class="continue-link" href="{{ url('tienda') }}">Seguir comprando</a></form></aside>
</div></div></main>
@endsection
@push('page_scripts')
<script src="{{ url('template/website/assets/js/carrito.js') }}?v=5"></script><script>document.addEventListener('DOMContentLoaded',function(){var cart=[];try{cart=JSON.parse(localStorage.getItem('fitness_club_tunja_cart')||'[]')}catch(e){}var empty=document.getElementById('cart-empty'),content=document.getElementById('cart-content'),form=document.getElementById('checkout-form'),items=document.getElementById('checkout-items');if(!cart.length){empty.hidden=false;content.hidden=true;form.hidden=true}else if(items){items.value=JSON.stringify(cart.filter(function(i){return i.id}).map(function(i){return{id:i.id,quantity:Math.max(1,Number(i.quantity)||1)}}))}if(form){form.addEventListener('submit',function(event){var valid=cart.filter(function(i){return i.id});if(!valid.length){event.preventDefault();alert('El carrito no tiene productos válidos. Regresa a la tienda y agrégalos nuevamente.');return}items.value=JSON.stringify(valid.map(function(i){return{id:i.id,quantity:Math.max(1,Number(i.quantity)||1)}}));form.querySelector('button[type=submit]').disabled=true;});}})</script>
@endpush
