@extends('website.layouts.app')
@section('title','Membresías | Fitness Club Tunja')
@section('seo_description','Elige la membresía ideal para entrenar en Fitness Club Tunja.')
@section('seo_canonical',url('membresias'))
@push('page_styles')
<style>
body{background:radial-gradient(circle at top,#101026,#050509)!important;color:#fff}.membership-store{padding:72px 0 110px}.membership-header{text-align:center;max-width:760px;margin:0 auto 48px}.membership-header h1{font-size:clamp(2rem,5vw,3.3rem);font-weight:900;text-transform:uppercase;background:linear-gradient(90deg,#8a2be2,#00f0ff);-webkit-background-clip:text;-webkit-text-fill-color:transparent}.membership-header p{color:#aaa}.plans-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(235px,1fr));gap:20px;max-width:1050px;margin:auto}.plan-card{display:flex;flex-direction:column;min-height:320px;padding:26px;background:#151527;border:1px solid rgba(255,255,255,.1);border-radius:18px;box-shadow:0 15px 32px rgba(0,0,0,.25)}.plan-card:hover{border-color:#00e5ff;transform:translateY(-4px)}.plan-card h2{margin:0 0 8px;text-transform:uppercase;font-size:1.2rem}.plan-price{font-size:2rem;color:#00e5ff;font-weight:900}.plan-duration{color:#85859b;font-size:.85rem;margin-bottom:18px}.plan-description{color:#bbb;line-height:1.55;flex:1;font-size:.9rem}.plan-add,.cart-link{border:0;border-radius:25px;padding:13px 18px;background:linear-gradient(90deg,#8a2be2,#00dff5);color:#fff;font-weight:800;text-transform:uppercase;text-align:center;cursor:pointer;text-decoration:none}.cart-bar{position:sticky;bottom:18px;z-index:5;display:flex;align-items:center;justify-content:space-between;gap:20px;max-width:1050px;margin:30px auto 0;padding:15px 20px;background:#18182b;border:1px solid rgba(0,229,255,.35);border-radius:14px;box-shadow:0 12px 30px rgba(0,0,0,.4)}.cart-bar small{display:block;color:#aaa}.cart-bar strong{color:#00e5ff;font-size:1.15rem}@media(max-width:600px){.cart-bar{align-items:stretch;flex-direction:column}.cart-link{width:100%}}
</style>
@endpush
@section('content')
<main class="membership-store"><div class="container">
<header class="membership-header"><h1>Elige tu membresía</h1><p>Selecciona un plan y continúa al carrito para revisar los detalles antes de pagar.</p></header>
<section class="plans-grid" aria-label="Membresías disponibles">
@forelse($membresias as $plan)<article class="plan-card"><h2>{{ $plan->nombre }}</h2><div class="plan-price">${{ number_format($plan->costo,0,',','.') }}</div><div class="plan-duration">{{ $plan->duracion }} {{ $plan->tipo_duracion }}</div><div class="plan-description">{!! $plan->descripcion ?: 'Acceso a nuestras instalaciones y acompañamiento para tu entrenamiento.' !!}</div><button class="plan-add" type="button" data-id="{{ $plan->id }}" data-name="{{ $plan->nombre }}" data-price="{{ $plan->costo }}" data-duration="{{ $plan->duracion }} {{ $plan->tipo_duracion }}">Agregar al carrito</button></article>@empty<p>No hay membresías disponibles.</p>@endforelse
</section>
<div class="cart-bar"><div><small id="cart-status">Tu carrito está vacío</small><strong id="cart-total"></strong></div><a class="cart-link" id="cart-link" href="{{ route('website.membresias.carrito') }}" hidden>Revisar carrito</a></div>
</div></main>
@endsection
@push('page_scripts')
<script>(function(){const key='fitness_club_membership_cart',cartUrl='{{ route('website.membresias.carrito') }}',status=document.getElementById('cart-status'),total=document.getElementById('cart-total'),link=document.getElementById('cart-link');let cart=null;try{cart=JSON.parse(localStorage.getItem(key)||'null')}catch(e){}function render(){if(!cart){status.textContent='Tu carrito está vacío';total.textContent='';link.hidden=true;return}status.textContent=cart.name;total.textContent='$'+Number(cart.price).toLocaleString('es-CO');link.hidden=false}document.querySelectorAll('.plan-add').forEach(function(b){b.addEventListener('click',function(){b.disabled=true;b.textContent='Abriendo carrito...';cart={id:b.dataset.id,name:b.dataset.name,price:b.dataset.price,duration:b.dataset.duration};localStorage.setItem(key,JSON.stringify(cart));window.location.assign(cartUrl)})});render()})()</script>
@endpush
